Fixed: Upstart/SysV init - Interoperability

diff --git a/configs/debian/php-fpm/php5-fpm b/configs/debian/php-fpm/php5-fpm
--- a/configs/debian/php-fpm/php5-fpm
+++ b/configs/debian/php-fpm/php5-fpm
@@ -6,7 +6,7 @@
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: starts php5-fpm
-# Description:       Starts PHP5 FastCGI Process Manager Daemon
+# Description:       Starts The PHP FastCGI Process Manager Daemon
 ### END INIT INFO
 
 # Author: Ondrej Sury <ondrej@debian.org>
@@ -15,7 +15,7 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="PHP5 FastCGI Process Manager"
 NAME=php5-fpm
 DAEMON=/usr/sbin/$NAME
-DAEMON_ARGS="--fpm-config /etc/php5/fpm/php-fpm.conf"
+DAEMON_ARGS="--daemonize --fpm-config /etc/php5/fpm/php-fpm.conf"
 PIDFILE=/var/run/php5-fpm.pid
 TIMEOUT=30
 SCRIPTNAME=/etc/init.d/$NAME
@@ -33,20 +33,27 @@ SCRIPTNAME=/etc/init.d/$NAME
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
+if type init_is_upstart | grep -q "function" ; then
+	# Don't run if we are running upstart
+	if init_is_upstart; then
+		exit 1
+	fi
+fi
+
 #
 # Function to check the correctness of the config file
 #
 do_check()
 {
-    [ "$1" != "no" ] && $DAEMON $DAEMON_ARGS -t 2>&1 | grep -v "\[ERROR\]"
-    FPM_ERROR=$($DAEMON $DAEMON_ARGS -t 2>&1 | grep "\[ERROR\]")
+	[ "$1" != "no" ] && $DAEMON $DAEMON_ARGS -t 2>&1 | grep -v "\[ERROR\]"
+	FPM_ERROR=$($DAEMON $DAEMON_ARGS -t 2>&1 | grep "\[ERROR\]")
 
-    if [ -n "${FPM_ERROR}" ]; then
-	echo "Please fix your configuration file..."
-	$DAEMON $DAEMON_ARGS -t 2>&1 | grep "\[ERROR\]"
-	return 1
-    fi
-    return 0
+	if [ -n "${FPM_ERROR}" ]; then
+		echo "Please fix your configuration file..."
+		$DAEMON $DAEMON_ARGS -t 2>&1 | grep "\[ERROR\]"
+		return 1
+	fi
+	return 0
 }
 
 #
@@ -108,70 +115,70 @@ do_reload() {
 }
 
 case "$1" in
-    start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-	do_check $VERBOSE
-	case "$?" in
-	    0)
-		do_start
+	start)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+		do_check $VERBOSE
 		case "$?" in
-		    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+			0)
+				do_start
+				case "$?" in
+					0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+					2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+				esac
+			;;
+			1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 		esac
-		;;
-	    1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
 	;;
-    stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-	do_stop
-	case "$?" in
-		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-	esac
+	stop)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
 	;;
     status)
-        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-        ;;
-    check)
-        do_check yes
+		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
-    reload|force-reload)
-	log_daemon_msg "Reloading $DESC" "$NAME"
-	do_reload
-	log_end_msg $?
+	check)
+		do_check yes
+	;;
+	reload|force-reload)
+		log_daemon_msg "Reloading $DESC" "$NAME"
+		do_reload
+		log_end_msg $?
 	;;
     reopen-logs)
-	log_daemon_msg "Reopening $DESC logs" $NAME
-	if start-stop-daemon --stop --signal USR1 --oknodo --quiet \
-	    --pidfile $PIDFILE --exec $DAEMON
-	then
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
+		log_daemon_msg "Reopening $DESC logs" $NAME
+		if start-stop-daemon --stop --signal USR1 --oknodo --quiet \
+			--pidfile $PIDFILE --exec $DAEMON
+		then
+			log_end_msg 0
+		else
+			log_end_msg 1
+		fi
 	;;
-    restart)
-	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_stop
-	case "$?" in
-	  0|1)
-		do_start
+	restart)
+		log_daemon_msg "Restarting $DESC" "$NAME"
+		do_stop
 		case "$?" in
-			0) log_end_msg 0 ;;
-			1) log_end_msg 1 ;; # Old process is still running
-			*) log_end_msg 1 ;; # Failed to start
+			0|1)
+				do_start
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+			;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+			;;
 		esac
-		;;
-	  *)
-	  	# Failed to stop
-		log_end_msg 1
-		;;
-	esac
 	;;
-    *)
-	echo "Usage: $SCRIPTNAME {start|stop|status|check|restart|reload|force-reload|reopen-logs}" >&2
-	exit 1
+	*)
+		echo "Usage: $SCRIPTNAME {start|stop|status|check|restart|reload|force-reload|reopen-logs}" >&2
+		exit 1
     ;;
 esac
 
