Syncronisation
git-svn-id: https://i-mscp.svn.sourceforge.net/svnroot/i-mscp/branches/autoinstall@4858 15a38060-5cfe-4f5c-bf9d-b5d42b1378a7

diff --git a/configs/debian/init.d/imscp_daemon b/configs/debian/init.d/imscp_daemon
--- a/configs/debian/init.d/imscp_daemon
+++ b/configs/debian/init.d/imscp_daemon
@@ -1,163 +1,138 @@
 #!/bin/sh
 
-# i-MSCP a internet Multi Server Control Panel
+# i-MSCP - internet Multi Server Control Panel
+# Copyright (C) 2010 - 2011 by internet Multi Server Control Panel
 #
-# Copyright (C) 2006-2010 by isp Control Panel - http://ispcp.net
-# Copyright (C) 2010 by internet Multi Server Control Panel - http://i-mscp.net
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
 #
-# Version: $Id$
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
 #
-# The contents of this file are subject to the Mozilla Public License
-# Version 1.1 (the "License"); you may not use this file except in
-# compliance with the License. You may obtain a copy of the License at
-# http://www.mozilla.org/MPL/
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 #
-# Software distributed under the License is distributed on an "AS IS"
-# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
-# License for the specific language governing rights and limitations
-# under the License.
-#
-# The Original Code is "ispCP ω (OMEGA) a Virtual Hosting Control Panel".
-#
-# The Initial Developer of the Original Code is ispCP Team.
-# Portions created by Initial Developer are Copyright (C) 2006-2010 by
-# isp Control Panel. All Rights Reserved.
-#
-# Portions created by the i-MSCP Team are Copyright (C) 2010 by
-# internet Multi Server Control Panel. All Rights Reserved.
-#
-# The i-MSCP Home Page is:
-#
-#    http://i-mscp.net
-#
+# @category		i-MSCP
+# @copyright	2010 - 2011 by i-MSCP | http://i-mscp.net
+# @author		Daniel Andreca <sci2tech@gmail.com>
+# @version		SVN: $Id$
+# @link			http://i-mscp.net i-MSCP Home Site
+# @license		http://www.gnu.org/licenses/gpl-2.0.html GPL v2
 
 ### BEGIN INIT INFO
-# Provides:             imscp_daemon
-# Required-Start:       $local_fs $remote_fs $network imscp_network
-# Required-Stop:        $local_fs $remote_fs $network imscp_network
-# Should-Start:         $named $time sendmail
-# Should-Stop:          $named $time sendmail
-# Default-Start:        2 3 4 5
-# Default-Stop:         0 1 6
-# Short-Description:    i-MSCP GUI-Backend communication Daemon
+# Provides:          imscp_daemon
+# Required-Start:    $local_fs $remote_fs $network $syslog imscp_network
+# Required-Stop:     $local_fs $remote_fs $network $syslog imscp_network
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: i-MSCP GUI-Backend communication Daemon
+# Description:       i-MSCP GUI-Backend communication Daemon
 ### END INIT INFO
 
-# Note: do not modify any of these vars here, use /etc/default/$NAME instead
-
-PATH=/sbin:/bin:/usr/sbin:/usr/bin
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="i-MSCP GUI-Backend communication Daemon"
 NAME=imscp_daemon
 DAEMON=/var/www/imscp/daemon/$NAME
-PID=/var/run/$NAME.pid
-DESC="i-MSCP GUI-Backend communication Daemon"
-LOGDIR=/var/log/imscp
-LOGFILE=${LOGDIR}/${NAME}.log
-DIETIME=3
+PIDFILE=/var/run/$NAME.pid
+DAEMON_ARGS="-p /var/run/$NAME.pid"
+SCRIPTNAME=/etc/init.d/$NAME
 
-START=1
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-umask 027
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# Debian LSB extensions (will be used if init-functions doesn't override them):
-log_daemon_msg() {
-	if [ ! -z "${2:-}" ]; then
-		log_success_msg "${1:-}: ${2:-}"
-	else
-		log_success_msg "${1:-}"
-	fi
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
 }
-log_end_msg() {
-	local status="$1"
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	start-stop-daemon --stop --quiet --oknodo --retry=TERM/5/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
-
-# if not present (e.g. *BSD) make sure to provide compatible methods via /etc/default/$NAME
-if [ -f /lib/lsb/init-functions ]; then
-	. /lib/lsb/init-functions
-fi
-
-test -x $DAEMON || {
-	if [ "$1" = "stop" ]; then
-		log_warning_msg "$DAEMON not installed, but stopping anyway."
-	else
-		exit 5
-	fi }
-
-# Read config file if present.
-if [ -r /etc/default/$NAME ]; then
-	. /etc/default/$NAME
-fi
-
-if [ $START -eq 0 ]; then
-	log_warning_msg "Not starting $DESC: edit /etc/default/$NAME."
-	exit 1
-fi
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC" "$NAME"
-
-	start_daemon -p $PID $DAEMON -p $PID
-
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-	log_daemon_msg "Stopping $DESC" "$NAME"
-
-	killproc -p $PID $DAEMON
-
-	log_end_msg $?
-
-	[ ! -f "$PID" ] || rm -f $PID
-	;;
-  restart|force-reload)
-	log_daemon_msg "Stopping $DESC" "$NAME"
-
-	killproc -p $PID $DAEMON
-
-	log_end_msg $?
-
-	[ ! -f "$PID" ] || rm -f $PID
-
-	[ -n "$DIETIME" ] && sleep "$DIETIME"
-
-	log_daemon_msg "Starting $DESC" "$NAME"
-
-	start_daemon -p $PID $DAEMON -- -p $PID
-
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   status)
-	log_daemon_msg "Checking status of $DESC"
-
-	pidofproc $DAEMON
-
-	status="$?"
-	log_end_msg "$status"
-
-	case "$status" in
-		0)
-			log_success_msg "$NAME running"
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  restart|force-reload)
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
 		;;
-		1)
-			log_warning_msg "$NAME not running (but pid file found)"
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
 		;;
-		2)
-			log_warning_msg "$NAME not running (but lock file found)"
-		;;
-		3)
-			log_warning_msg "$NAME not running"
-		;;
-		4|*)
-			log_failure_msg "Service status is unknown"
-			exit 1
-		;;
-        esac
+	esac
 	;;
-
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
-	exit 1
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
 	;;
 esac
 
-exit 0
+:
