Some file reorganisation
git-svn-id: https://i-mscp.svn.sourceforge.net/svnroot/i-mscp/trunk@3933 15a38060-5cfe-4f5c-bf9d-b5d42b1378a7

diff --git a/library/shell/so-functions b/library/shell/so-functions
--- a/library/shell/so-functions
+++ b/library/shell/so-functions
@@ -26,30 +26,40 @@
 # @category		i-MSCP
 # @copyright	2010 by i-MSCP | http://i-mscp.net
 # @author		Daniel Andreca <sci2tech@i-mscp.net>
-# @version		SVN: $Id$
+# @version		SVN: $Id: so-functions 3917 2010-11-30 21:20:52Z sci2tech $
 # @link			http://i-mscp.net i-MSCP Home Site
 # @license		http://www.gnu.org/licenses/ GPL v2
 
-SYSTEM_FOLDERS='
-				INST_PREF=/tmp/imscp
-				ROOT_CONF=${INST_PREF}/etc
-				SYSTEM_ROOT=${INST_PREF}/var/www/imscp
-				SYSTEM_CONF=${INST_PREF}/etc/imscp
-				SYSTEM_LOG=${INST_PREF}/var/log/imscp
-				SYSTEM_APACHE_BACK_LOG=${INST_PREF}/var/log/httpd/backup
-				SYSTEM_VIRTUAL=${INST_PREF}/var/www/virtual
-				SYSTEM_AWSTATS=${INST_PREF}/var/www/awstats
-				SYSTEM_FCGI=${INST_PREF}/var/www/fcgi
-				SYSTEM_SCOREBOARDS=${INST_PREF}/var/www/scoreboards
-				SYSTEM_MAIL_VIRTUAL=${INST_PREF}/var/mail/virtualtual
+# detect_os() {{{
+#
+# Determine operating system saving in script wide variale HOST_OS
+# If SO is Linux also save flavour as DIST, version as VER and codename as CODENAME
+# @return	void
+detect_os() {
+	HOST_OS=$(uname)
+	# If error executing uname exit
+	if [ $? -ne 0 ];then printf "Can not guess operating system"; failtxt 'fail'; exit 1; fi
+	if [ "${HOST_OS}" = "FreeBSD" ]; then
+		export DIST="FreeBSD"
+	elif [ "${HOST_OS}" = "OpenBSD" ]; then
+		export DIST="OpenBSD"
+	elif [ "${HOST_OS}" = "Linux" ]; then
+		# get lsb_version full path in $lsb_variable
+		testCommand "lsb_release"
+		export DIST=$($lsb_release -si)
+		export VER=$($lsb_release -sr)
+		export CODENAME=$($lsb_release -sc)
+	fi
+}
+# }}}
 
-				ROOT_APACHE_CONF=${ROOT_CONF}/httpd/
-
-				ROOT_COURIER_CONF=${ROOT_CONF}/courier
-				ROOT_AUTHLIB_CONF=${ROOT_CONF}/authlib
-
-				ROOT_POSTFIX_CONF=${ROOT_CONF}/postfix
-'
-FOLDERS='${SYSTEM_LOG}/imscp-arpl-msgr'
-COPY_FILE=''
-CREATE_FILE=''
+# testroot() {{{
+#
+# Check if script is running as root user if not exit
+# @return	void
+testroot(){
+	title 'Testing for root'
+	local _ERR='You must be root to install'
+	if [ $(id -u) -ne 0 ]; then msgbox "$_ERR"; failtxt "$_ERR"; fi
+}
+# }}}
