* [DISTS] OpenSuse - Removed several useless information displayed on STDIN  * [DISTS] OpenSuse - Removed useless tasks in the postinst script  * [DISTS] OpenSuse - removed useless 'update' argument for postinst script  * [SETUP] Added automatic call for maintainer's postinst scripts  * [SETUP] Moved call of postinst script in ispcp-update (restarting services  should be done after)
git-svn-id: https://i-mscp.svn.sourceforge.net/svnroot/i-mscp/trunk@2722 15a38060-5cfe-4f5c-bf9d-b5d42b1378a7

diff --git a/docs/OpenSuse/postinst b/docs/OpenSuse/postinst
--- a/docs/OpenSuse/postinst
+++ b/docs/OpenSuse/postinst
@@ -5,7 +5,7 @@
 # ispCP ω (OMEGA) a Virtual Hosting Control Panel
 # Copyright (C) 2006-2009 by isp Control Panel - http://ispcp.net
 # author        Laurent Declercq <laurent.declercq@ispcp.net>
-# version		1.2
+# version		1.3
 #
 # SVN: $Id$
 #
@@ -32,12 +32,13 @@
 
 # Special note for DevTeam:
 #
-# It is necessary for the error recovery and update procedures that the scripts be idempotent.
-# This means that if it is run successfully, and then it is called again, it doesn't
-# bomb out or cause any harm, but just ensures that everything is the way it ought to be.
-# If the first call failed, or aborted half way through for some reason, the second call
-# should merely do the things that were left undone the first time, if any, and exit with
-# a success status if if everything is OK.
+# It is necessary for the error recovery and update procedures that the scripts 
+# be idempotent. This means that if it is run successfully, and then it is
+# called again, it doesn't bomb out or cause any harm, but just ensures that
+# everything is the way it ought to be. If the first call failed, or aborted
+# half way through for some reason, the second call should merely do the things
+# that were left undone the first time, if any, and exit with a success status
+# if if everything is OK.
 
 set -e
 
@@ -45,10 +46,11 @@ CONF_FILE=/etc/ispcp/ispcp.conf
 
 if [ ! -f $CONF_FILE ] ; then
  echo "E: $CONF_FILE not found!"
+ echo "Fix the problem and try to execute the ispcp-update script!"
  exit 1
 fi
 
-# read needed entries from ispcp.conf
+# Read needed entries from ispcp.conf
 for a in `grep -E '(^Version|APACHE_|MTA_|ROOT_|^PHP_FASTCGI|^CMD_|^DEBUG)' $CONF_FILE | sed -e 's/ //g'`; do
     export $a
 done
@@ -57,9 +59,15 @@ A2ENMOD=/usr/sbin/a2enmod
 A2DISMOD=/usr/sbin/a2dismod
 CMD_MD5=/usr/bin/md5sum
 INSSERV="/sbin/insserv -d"
+
+# List of service required by ispCP
 SERVICES="$CMD_ISPCPN $CMD_ISPCPD fam $CMD_NAMED apache2 $CMD_FTPD postgrey policyd-weight $CMD_MTA $CMD_AUTHD $CMD_IMAP $CMD_IMAP_SSL $CMD_POP $CMD_POP_SSL mysql"
-ISPCP_VERS=`echo $Version | sed -e 's/[A-Z]//g'`
-DIST_VERS=`grep -E '^VERSION' /etc/SuSE-release | sed -e 's/[[:space:]=A-Z]//g'`
+
+# Get ispCP version (not used at this moment)
+#ISPCP_VERS=`echo $Version | sed -e 's/[A-Z]//g'`
+
+# Get Dist release version (not used at this moment)
+#DIST_VERS=`grep -E '^VERSION' /etc/SuSE-release | sed -e 's/[[:space:]=A-Z]//g'`
 
 if [ $DEBUG -eq 1 ]; then
   echo "now debugging $0 $@"
@@ -68,168 +76,184 @@ fi
 
 case "$1" in
 
-        configure)
-        	echo "ispCP Post Installation - Starting"
+	configure)
 
-			# Stop all services
-			echo " Stop all services"
-			for service in $SERVICES ; do
-				[ -f "/etc/init.d/$service" ] && /etc/init.d/$service stop || true
-			done
+	#
+	## OpenSuSE firewall configuration - Begin
+	#
 
-			#
-			# OpenSuSE firewall configuration
-			#
-			echo " OpenSuSE Firewall Configuration"
+	echo -e "\t\tOpenSuSE Firewall Configuration"
 
-			echo "  Stop firewall service"
-			[ -f /etc/init.d/SuSEfirewall2_setup ] && /etc/init.d/SuSEfirewall2_setup stop
-			echo "  Disabling automatic start"
-			[ -f /sbin/yast2 ] && /sbin/yast2 firewall startup manual
+	[ -f /etc/init.d/SuSEfirewall2_setup ] && /etc/init.d/SuSEfirewall2_setup stop
+	[ -f /sbin/yast2 ] && /sbin/yast2 firewall startup manual
 
-			#
-			# Apache2 Configuration
-			#
-			echo " Apache Configuration Processing"
+	#
+	## OpenSuSE firewall configuration - End
+	#
 
-			if [ -f /usr/sbin/suexec2 ] ; then
-				echo "  Fixing suexec wrapper owner/group and permissions"
-				$CMD_CHOWN $ROOT_USER:$APACHE_GROUP /usr/sbin/suexec2
-				$CMD_CHMOD 4755 /usr/sbin/suexec2
-			fi
+	#
+	## Apache2 Configuration - Begin
+	#
 
-			# Enable FastCGI module (fcgid|fascgi) and disable unused
-			if [ ! -z "$PHP_FASTCGI" ] ; then
-				echo "  Enable fastcgi ($PHP_FASTCGI) module if not already present"
-				if [ "$PHP_FASTCGI" == "fcgid" ]; then
-					[ -x $A2ENMOD ] && $A2ENMOD $PHP_FASTCGI
-					[ -x $A2DISMOD ] && $A2DISMOD fastcgi
-				else
-					[ -x $A2ENMOD ] && $A2ENMOD $PHP_FASTCGI
-					[ -x $A2DISMOD ] && $A2DISMOD fcgid
-				fi
-			fi
+	echo -e "\t\tApache Configuration Processing"
 
-			# Disable default FastCGI modules configuration files
-			echo "  Disable default fastcgi module configuration file if needed"
-			[ -f /etc/apache2/conf.d/mod_fastcgi.conf ] && $CMD_MV /etc/apache2/conf.d/mod_fastcgi.conf /etc/apache2/conf.d/mod_fastcgi.conf.disabled
-			echo "  Disable default fcgid module configuration file if needed"
-			[ -f /etc/apache2/conf.d/mod_fcgid.conf ] && $CMD_MV /etc/apache2/conf.d/mod_fcgid.conf /etc/apache2/conf.d/mod_fcgid.conf.disabled
+	if [ -f /usr/sbin/suexec2 ] ; then
+		$CMD_CHOWN $ROOT_USER:$APACHE_GROUP /usr/sbin/suexec2
+		$CMD_CHMOD 4755 /usr/sbin/suexec2
+	fi
 
-			# Disable mod php5
-			echo "  Disable php5 module"
-			[ -x $A2DISMOD ] && $A2DISMOD php5
+	#
+	## Apache2 Configuration - End
+	#
 
-			#
-			# Postfix Configuration
-			#
-			echo " Postfix Configuration Processing"
+	#
+	## FastCGI Apache module Configuration - Begin
+	#
 
-			# Fix warning: "not owned by root: /var/spool/postfix"
-			# This is because the postgrey package changes the
-			# owner of this directory dunring installation (why ?)
-			echo "  Fix owner to root for the /var/spool/postfix directory"
-			$CMD_CHOWN root:postfix /var/spool/postfix
+	echo -e "\t\tFastCGI module configuration"
 
-			# Sasl postfix configuration
-			echo "  Postfix/Sasl configuration for ispCP"
+	# Enable FastCGI module (fcgid|fascgi) and disable unused
+	if [ ! -z "$PHP_FASTCGI" ] ; then
+		if [ "$PHP_FASTCGI" == "fcgid" ]; then
+			[ -x $A2ENMOD ] && $A2ENMOD $PHP_FASTCGI
+			[ -x $A2DISMOD ] && $A2DISMOD fastcgi
+		else
+			[ -x $A2ENMOD ] && $A2ENMOD $PHP_FASTCGI
+			[ -x $A2DISMOD ] && $A2DISMOD fcgid
+		fi
+	fi
 
-			if [ ! -f /etc/ispcp/postfix/backup/smtpd.conf.system -a \
-				   -f /etc/sasl2/smtpd.conf ]; then
-				echo "   Backup $MTA_SASL_CONF_FILE dist file"
-				$CMD_CP -a /etc/sasl2/smtpd.conf /etc/ispcp/postfix/backup/smtpd.conf.system
-				$CMD_CHMOD 0600 /etc/ispcp/postfix/backup/smtpd.conf.system
-			fi
+	# Disable default FastCGI modules configuration files
+	[ -f /etc/apache2/conf.d/mod_fastcgi.conf ] && $CMD_MV /etc/apache2/conf.d/mod_fastcgi.conf /etc/apache2/conf.d/mod_fastcgi.conf.disabled
+	[ -f /etc/apache2/conf.d/mod_fcgid.conf ] && $CMD_MV /etc/apache2/conf.d/mod_fcgid.conf /etc/apache2/conf.d/mod_fcgid.conf.disabled
 
-			# First we build a new conffile with available smtpd.conf template
-			echo "   Generating new smtpd.conf file from template"
-			($CMD_CAT /etc/ispcp/postfix/smtpd.conf) |
-			$CMD_SED "
-						s/{MTA_SASL_LOG_LEVEL}/$MTA_SASL_LOG_LEVEL/
-						s/{MTA_SASL_PWCHECK_METHOD}/$MTA_SASL_PWCHECK_METHOD/
-						s/{MTA_SASL_MECH_LIST}/$(echo $MTA_SASL_MECH_LIST | sed 's/,/ /g')/
-					 " >/tmp/smtpd.conf.tmp
+	#
+	## FastCGI Apache module Configuration - Begin
+	#
 
-			if [ "$MTA_SASL_AUXPROP_PLUGIN" != "no" ]; then
-				$CMD_SED -i "s/{MTA_SASL_AUXPROP_PLUGIN}/$MTA_SASL_AUXPROP_PLUGIN/" /tmp/smtpd.conf.tmp
-			else
-				$CMD_SED -i '/auxprop_plugin: {MTA_SASL_AUXPROP_PLUGIN}/d' /tmp/smtpd.conf.tmp
-			fi
+	#
+	## PHP configuration - Begin
+	#
 
-			# Update configuration file if needed
-			if [ -f "$MTA_SASL_CONF_FILE" ] ; then
-				oldmd5=`$CMD_MD5 $MTA_SASL_CONF_FILE | cut -d' ' -f1`
-				newmd5=`$CMD_MD5 /tmp/smtpd.conf.tmp | cut -d' ' -f1`
-				if [ "$oldmd5" != "$newmd5" ]; then
-					echo "   Update $MTA_SASL_CONF_FILE configuration file"
-					$CMD_CP -p /tmp/smtpd.conf.tmp /etc/ispcp/postfix/backup/smtpd.conf.ispcp
-				fi
-			fi
+	echo -e "\t\tPHP configuration"
 
-			$CMD_CP -p /etc/ispcp/postfix/backup/smtpd.conf.ispcp $MTA_SASL_CONF_FILE
-			$CMD_CHMOD 0600 $MTA_SASL_CONF_FILE /etc/ispcp/postfix/backup/smtpd.conf.ispcp
+	# Disable mod php5
+	[ -x $A2DISMOD ] && $A2DISMOD php5
 
-			#
-			# Postgrey Configuration
-			#
-			echo " Postgrey Configuration Processing"
+	#
+	## PHP configuration - End
+	#
 
-			if [ -f /etc/sysconfig/postgrey ] ; then
-				echo "  Changing the listening port of postgrey to 60000"
-				$CMD_SED -i 's/#POSTGREY_CONN_OPTIONS="--inet=127.0.0.1:10031"/POSTGREY_CONN_OPTIONS="--inet=127.0.0.1:60000"/' /etc/sysconfig/postgrey
-				echo "  Disable unix socket (we use TCP connection instead)"
-				$CMD_SED -i 's/POSTGREY_CONN_OPTIONS="--unix=\/var\/spool\/postfix\/postgrey\/socket"/#POSTGREY_CONN_OPTIONS="--unix=\/var\/spool\/postfix\/postgrey\/socket"/' /etc/sysconfig/postgrey
-			fi
-			
-			# 
-			# rkhunter 
-			# 
-			echo " Building rkhunter database" 
-			/usr/bin/rkhunter --propupd &
+	#
+	## Postfix Configuration - Begin
+	#
 
-			#
-			# Courier-Authentication Configuration
-			#
-			echo " Courier-Authentication Configuration Processing"
+	echo "\t\tPostfix Configuration Processing"
 
-			# Prevent authdaemon warnings related to missing modules in mail log files
-			if [ -f /etc/authlib/authdaemonrc ] ; then
-				echo "  Prevent authdaemond warning related to missing modules"
-				$CMD_SED -i 's/authmodulelist="authuserdb authuserdb authpam authpgsql authldap authmysql authcustom authpipe"/authmodulelist="authuserdb authpam authcustom"/' /etc/authlib/authdaemonrc
-			fi
+	# Fix warning: "not owned by root: /var/spool/postfix"
+	# This is because the postgrey package changes the
+	# owner of this directory during installation (why ?)
+	$CMD_CHOWN root:postfix /var/spool/postfix
 
-			#
-			# System Init Configuration
-			#
-			echo " System Init configuration"
+	# Sasl postfix configuration
+	if [ ! -f /etc/ispcp/postfix/backup/smtpd.conf.system -a \
+	    -f /etc/sasl2/smtpd.conf ]; then
+		$CMD_CP -a /etc/sasl2/smtpd.conf /etc/ispcp/postfix/backup/smtpd.conf.system
+		$CMD_CHMOD 0600 /etc/ispcp/postfix/backup/smtpd.conf.system
+	fi
 
-			# Enable all system init scripts needed by ispCP
-			echo "  Enable all system init scripts needed by ispCP"
-			for service in $SERVICES ; do
-				echo "   Enable $service init script..."
-				[ -f /etc/init.d/$service ] && $INSSERV $service
-			done
+	# First we build a new conffile with available smtpd.conf template
+	($CMD_CAT /etc/ispcp/postfix/smtpd.conf) |
+	$CMD_SED "
+				s/{MTA_SASL_LOG_LEVEL}/$MTA_SASL_LOG_LEVEL/
+				s/{MTA_SASL_PWCHECK_METHOD}/$MTA_SASL_PWCHECK_METHOD/
+				s/{MTA_SASL_MECH_LIST}/$(echo $MTA_SASL_MECH_LIST | sed 's/,/ /g')/
+	 " >/tmp/smtpd.conf.tmp
 
-			# Restart ispCP firewall
-			echo " Restart ispCP firewall"
-			[ -f /etc/init.d/ispcp_network ] && /etc/init.d/ispcp_network restart
+	if [ "$MTA_SASL_AUXPROP_PLUGIN" != "no" ]; then
+		$CMD_SED -i "s/{MTA_SASL_AUXPROP_PLUGIN}/$MTA_SASL_AUXPROP_PLUGIN/" /tmp/smtpd.conf.tmp
+	else
+		$CMD_SED -i '/auxprop_plugin: {MTA_SASL_AUXPROP_PLUGIN}/d' /tmp/smtpd.conf.tmp
+	fi
 
-			# Restart all services
-			sleep 1
+	# Update sasl configuration file if needed
+	if [ -f "$MTA_SASL_CONF_FILE" ] ; then
+		oldmd5=`$CMD_MD5 $MTA_SASL_CONF_FILE | cut -d' ' -f1`
+		newmd5=`$CMD_MD5 /tmp/smtpd.conf.tmp | cut -d' ' -f1`
+		if [ "$oldmd5" != "$newmd5" ]; then
+			$CMD_CP -p /tmp/smtpd.conf.tmp /etc/ispcp/postfix/backup/smtpd.conf.ispcp
+		fi
+	fi
 
-			echo " Restart all services"
-			for service in $SERVICES ; do
-				[ -f /etc/init.d/$service ] && /etc/init.d/$service start
-			done
-        	echo "ispCP Post Installation - Ending"
-        ;;
-        update)
-			./postinst configure
-        ;;
-        *)
-			echo "Usage: sh $0 {configure|update}"
-			exit 1
-        ;;
+	$CMD_CP -p /etc/ispcp/postfix/backup/smtpd.conf.ispcp $MTA_SASL_CONF_FILE
+	$CMD_CHMOD 0600 $MTA_SASL_CONF_FILE /etc/ispcp/postfix/backup/smtpd.conf.ispcp
+
+	#
+	## Postfix Configuration - End
+	#
+
+	#
+	## Postgrey Configuration - Begin
+	#
+
+	echo -e "\t\tPostgrey Configuration Processing"
+
+	if [ -f /etc/sysconfig/postgrey ] ; then
+		$CMD_SED -i 's/#POSTGREY_CONN_OPTIONS="--inet=127.0.0.1:10031"/POSTGREY_CONN_OPTIONS="--inet=127.0.0.1:60000"/' /etc/sysconfig/postgrey
+		$CMD_SED -i 's/POSTGREY_CONN_OPTIONS="--unix=\/var\/spool\/postfix\/postgrey\/socket"/#POSTGREY_CONN_OPTIONS="--unix=\/var\/spool\/postfix\/postgrey\/socket"/' /etc/sysconfig/postgrey
+	fi
+
+	#
+	## Postgrey Configuration - End
+	#
+
+	# 
+	## Rkhunter - Begin
+	# 
+
+	echo -e "\t\tBuilding rkhunter database (Background process)" 
+
+	/usr/bin/rkhunter --propupd &
+
+	# 
+	## Rkhunter - End
+	# 
+
+	#
+	## Courier-Authentication Configuration - Begin
+	#
+
+	echo -e "\t\tCourier-Authentication Configuration Processing"
+
+	# Prevent authdaemon warnings related to missing modules in mail log files
+	if [ -f /etc/authlib/authdaemonrc ] ; then
+		$CMD_SED -i 's/authmodulelist="authuserdb authuserdb authpam authpgsql authldap authmysql authcustom authpipe"/authmodulelist="authuserdb authpam authcustom"/' /etc/authlib/authdaemonrc
+	fi
+
+	#
+	## Courier-Authentication Configuration - End
+	#
+
+	#
+	## System Init Configuration - Begin
+	#
+
+	echo -e "\t\tSystem Init configuration"
+
+	# Enable all system init scripts needed by ispCP
+	for service in $SERVICES ; do
+		if [ -x "/etc/init.d/$service" ]; then
+			$INSSERV $service ||true
+		fi
+	done
+
+	#
+	## System Init Configuration - End
+	#
+	;;
+	*)
+	exit 0
+	;;
 esac
 
 exit 0
