Changed: Frontend is now run through an isolated PHP-FPM master process (see errata file) Fixed: Running the frontEnd through PHP CGI using spawn-fcgi lead to problems with opcode cache (see errata file) Small fixes [ci skip]

diff --git a/configs/debian/sysvinit/imscp_panel b/configs/debian/sysvinit/imscp_panel
--- a/configs/debian/sysvinit/imscp_panel
+++ b/configs/debian/sysvinit/imscp_panel
@@ -1,33 +1,29 @@
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          imscp_panel
-# Required-Start:    $local_fs $network
-# Required-Stop:     $local_fs $network
+# Required-Start:    $remote_fs $network
+# Required-Stop:     $remote_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: i-MSCP frontEnd PHP processes
+# Short-Description: starts imscp_panel
+# Description:       PHP FastCGI process Manager Daemon for i-MSCP FrontEnd
 ### END INIT INFO
 
-# Author: Laurent Declercq <l.declercq@nuxwin.com>
-
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
-DESC="i-MSCP frontEnd PHP FCGI processes"
+DESC="# Author: Ondrej Sury <ondrej@debian.org>"
 NAME=imscp_panel
-STARTER=/var/www/fcgi/master/php-fcgi-starter
-DAEMON=/usr/bin/php5-cgi
-PIDFILE=/var/run/$NAME.pid
+DAEMON=/usr/local/sbin/$NAME
+DAEMON_ARGS="--daemonize --fpm-config /usr/local/etc/imscp_panel/php-fpm.conf -c /usr/local/etc/imscp_panel/php.ini"
+CONF_PIDFILE=$(sed -n 's/^pid\s*=\s*//p' /usr/local/etc/imscp_panel/php-fpm.conf)
+PIDFILE=${CONF_PIDFILE:-/run/imscp_panel.pid}
 TIMEOUT=30
 SCRIPTNAME=/etc/init.d/$NAME
-MASTER_WEB_USER=vu2000
 
-# Exit if the package is not installed
+# Exit if the daemon is not installed
 [ -x "$DAEMON" ] || exit 0
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
-
-# Check for Master Web user existence
-[ -n "`grep ^$MASTER_WEB_USER: /etc/passwd`" ] || exit 0
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -46,21 +42,31 @@ check_for_upstart()
 }
 
 #
+# Function to check the correctness of the config file
+#
+do_check()
+{
+    /usr/local/lib/imscp_panel/imscp_panel_checkconf || return 1
+    return 0
+}
+
+#
 # Function that starts the daemon/service
 #
 do_start()
 {
-        # Return
-        #   0 if daemon has been started
-        #   1 if daemon was already running
-        #   2 if daemon could not be started
-        start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $STARTER --exec $DAEMON --test > /dev/null \
-                || return 1
-        start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $STARTER --exec $DAEMON 2>/dev/null \
-                || return 2
-        # Add code here, if necessary, that waits for the process to be ready
-        # to handle requests from services started subsequently which depend
-        # on this one.  As a last resort, sleep for some time.
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+		$DAEMON_ARGS 2>/dev/null \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
 #
@@ -68,75 +74,113 @@ do_start()
 #
 do_stop()
 {
-        # Return
-        #   0 if daemon has been stopped
-        #   1 if daemon was already stopped
-        #   2 if daemon could not be stopped
-        #   other if a failure occurred
-        start-stop-daemon --stop --quiet --retry=QUIT/$TIMEOUT/TERM/5/KILL/5 --pidfile $PIDFILE \
-            --user $MASTER_WEB_USER --exec $DAEMON
-        RETVAL="$?"
-        [ "$RETVAL" = 2 ] && return 2
-        # Wait for children to finish too if this is a daemon that forks
-        # and if the daemon is only ever run from this initscript.
-        # If the above conditions are not satisfied then add some other code
-        # that waits for the process to drop all resources that could be
-        # needed by services started subsequently.  A last resort is to
-        # sleep for some time.
-        start-stop-daemon --stop --quiet --oknodo --retry=0/30/TERM/5/KILL/5 --user $MASTER_WEB_USER --exec $DAEMON
-        [ "$?" = 2 ] && return 2
-        # Many daemons don't delete their pidfiles when they exit.
-        rm -f $PIDFILE
-        return "$RETVAL"
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=QUIT/$TIMEOUT/TERM/5/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/TERM/5/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal USR2 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
 }
 
 case "$1" in
-  start)
-    check_for_upstart 1
-    log_daemon_msg "Starting $DESC" "$NAME"
-    rm -f /var/run/imscp_panel.sock
-    do_start
-    case "$?" in
-        0|1) log_end_msg 0 ;;
-        2) log_end_msg 1 ;;
-    esac
-    ;;
-  stop)
-    check_for_upstart 0
-    log_daemon_msg "Stopping $DESC" "$NAME"
-    do_stop
-    case "$?" in
-        0|1) log_end_msg 0 ;;
-        2) log_end_msg 1 ;;
-    esac
-    ;;
-  restart|force-reload)
-    check_for_upstart 1
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-            0) log_end_msg 0 ;;
-            1) log_end_msg 1 ;; # Old process is still running
-            *) log_end_msg 1 ;; # Failed to start
-        esac
-        ;;
-      *)
-        # Failed to stop
-        log_end_msg 1
-        ;;
-    esac
-    ;;
-  status)
-    check_for_upstart 1
-    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-    ;;
-  *)
-    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
-    exit 3
-    ;;
+	start)
+	check_for_upstart 1
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_check $VERBOSE
+	case "$?" in
+		0)
+		do_start
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+		;;
+		1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+	stop)
+	check_for_upstart 0
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+	status)
+	check_for_upstart 1
+		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+		;;
+	check)
+	check_for_upstart 1
+		do_check yes
+	;;
+	reload|force-reload)
+	check_for_upstart 1
+	log_daemon_msg "Reloading $DESC" "$NAME"
+	do_reload
+	log_end_msg $?
+	;;
+	reopen-logs)
+	check_for_upstart 1
+	log_daemon_msg "Reopening $DESC logs" $NAME
+	if start-stop-daemon --stop --signal USR1 --oknodo --quiet \
+		--pidfile $PIDFILE --exec $DAEMON
+	then
+		log_end_msg 0
+	else
+		log_end_msg 1
+	fi
+	;;
+	restart)
+	check_for_upstart 1
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+	*)
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
+	exit 1
+	;;
 esac
 
 :
